# Generated by Django 5.0.6 on 2024-07-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='day',
            # field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=9),
            field=models.CharField(choices=[('Piyush', 'Piyush'), ('Piyush', 'Piyush'), ('Piyush', 'Piyush'), ('Piyush', 'Piyush'), ('Piyush', 'Piyush'), ('Piyush', 'Piyush'), ('Piyush', 'Piyush')], default='Monday', max_length=9),
        ),
        migrations.AddField(
            model_name='train',
            name='reaching_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='train',
            name='starting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='destination',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='train',
            name='start',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_name',
            field=models.CharField(max_length=255),
        ),
    ]
