# Generated by Django 5.0.6 on 2024-07-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0002_train_day_train_reaching_time_train_starting_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=9, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='train',
            name='day',
        ),
        migrations.AddField(
            model_name='train',
            name='days',
            field=models.ManyToManyField(to='trains.day'),
        ),
    ]
