# Generated by Django 5.0.6 on 2024-07-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_day_remove_train_day_train_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='name',
            field=models.CharField(choices=[('Sunday', 'Sunday'), ('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday')], default='Monday', max_length=9),
        ),
    ]
